name: Bash Task

on: push

env:
  REPO_NAME: itvtask
  S3_UPLOAD_PATH: s3://itvtask/viewing_product/
  RUN_TEST_COMMAND: pytest
  REPO_URL_PREFIX: ${{ secrets.REPO_URL_PREFIX }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.0

      - name: Run Bash script
        run: ./scripts/test_and_deploy_viewing_product.sh
